# Uncomment the next line to define a global platform for your project

source 'https://cdn.cocoapods.org/'


platform :ios, '12.0'


target 'BDAlphaPlayerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BDAlphaPlayerDemo
  pod 'BDAlphaPlayer', :path => '../../../'
  
  pod 'Masonry'
  
end


post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
